backend:
  name: github
  repo: Aaron-xi/myblog
  branch: main
  base_url: https://myblog-auth.jfkliuxi0303.workers.dev # 填入你的 Worker 地址
  auth_endpoint: /auth # 对应 Worker 里的路径

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "是否公开", name: "published", widget: "boolean", default: true } # 新增这一行
      - { label: "标签", name: "tags", widget: "list" }
      - { label: "正文", name: "body", widget: "markdown" }
